export const FETCH_WHEATHER_ERROR='FETCH_WHEATHER_ERROR'

export const FETCH_CURRENT_SUCCESS='FETCH_CURRENT_SUCCESS'
export const FETCH_FORECAST_SUCCESS='FETCH_FORECAST_SUCCESS'

export const FETCH_WHEATHER_PENDING='FETCH_WHEATHER_PENDING'
export const SET_CITY='SET_CITY';
